server {
    listen 80;

    server_name nktx.dev www.nktx.dev;

    root /var/www;
    index index.html;

    error_log  /var/log/nginx/http_error.log;
    access_log /var/log/nginx/http_access.log;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;

    server_name market-detail.nktx.dev;

    root /var/www/public;
    index index.php index.html;

    ssl_certificate /etc/letsencrypt/live/nktx.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/nktx.dev/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    error_log  /var/log/nginx/https_error.log;
    access_log /var/log/nginx/https_access.log;

    location ~ /\.(?!well-known).* {
        deny all;
    }

    location / {
        try_files $uri $uri/ /index.html?$query_string;
    }

    client_max_body_size 512M;
}